# Generated by Django 5.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100, null=True)),
                ('new_reading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_reading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('meter_type', models.CharField(max_length=100, null=True)),
                ('meter_status', models.BooleanField(default=True, null=True)),
                ('processed', models.BooleanField(default=False, null=True)),
                ('reading_date', models.DateField(null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer')),
            ],
        ),
    ]
