# Generated by Django 5.1 on 2024-10-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0002_alter_meter_meter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_reading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_reading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('meter_status', models.BooleanField(default=True, null=True)),
                ('processed', models.BooleanField(default=False, null=True)),
                ('reading_date', models.DateField(null=True)),
                ('meter_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='meter',
            name='last_reading',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='meter_status',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='new_reading',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='reading_date',
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
