# Generated by Django 5.1 on 2024-10-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0003_meterreading_remove_meter_last_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='meter_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
