# Generated by Django 5.1 on 2024-10-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0004_meterreading_meter_number_alter_meter_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.IntegerField(max_length=100, null=True, unique=True),
        ),
    ]
