# Generated by Django 5.1 on 2024-10-12 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0005_alter_meter_meter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='meter_number',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meterreader.meter'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
