# Generated by Django 5.1 on 2024-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0006_remove_meterreading_meter_number_meterreading_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meter_images/'),
        ),
    ]
