# Generated by Django 5.1 on 2024-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterreader', '0007_alter_meterreading_meter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
