# Generated by Django 5.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('meterreader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meterreader.meter'),
        ),
    ]
