# Generated by Django 5.1 on 2024-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_bill_gross_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='current_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
