# Generated by Django 5.1 on 2024-10-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SDO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=255, null=True, unique=True)),
                ('consumer_name', models.CharField(max_length=255, null=True)),
                ('consumer_address', models.TextField(null=True)),
                ('consumer_division', models.CharField(max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('consumer_tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SDO.tariff')),
            ],
        ),
    ]
