# Generated by Django 5.1 on 2024-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
