# Generated by Django 5.1 on 2024-10-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_alter_consumer_consumer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='meter_type',
            field=models.CharField(choices=[('single', 'Single Phase'), ('double', 'Double Phase'), ('three', 'Three Phase')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumer_division',
            field=models.CharField(choices=[('division1', 'Division 1'), ('division2', 'Division 2'), ('division3', 'Division 3')], max_length=255, null=True),
        ),
    ]
