# Generated by Django 5.1 on 2024-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDO', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(default=None, null=True)),
                ('year', models.PositiveIntegerField(default=None, null=True)),
                ('total_bills_generated', models.PositiveIntegerField(default=0)),
                ('total_units_consumed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
