# Generated by Django 5.1 on 2024-11-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDO', '0003_monthlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
