# Generated by Django 5.1 on 2024-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDO', '0004_alter_monthlyreport_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='total_consumers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_meter_assigned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_meter_readers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_office_staff',
            field=models.IntegerField(default=0),
        ),
    ]
